/* eslint-disable @next/next/no-before-interactive-script-outside-document */
import type { Metadata } from 'next';
import './globals.css';
import pretendardRegular from './_constants/font';
import { MSWProvider } from '@/public/mocks/MSWProvider';
import QueryProvider from './_providers/QueryProvider';

declare global {
  interface Window {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    kakao: any;
  }
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <QueryProvider>
        <MSWProvider>
          <body className={`${pretendardRegular.className} bg-gray`}>
            <div className="mx-auto min-h-screen max-w-[375px]">{children}</div>
          </body>
        </MSWProvider>
      </QueryProvider>
    </html>
  );
}
