import type { Metadata } from 'next';
import './globals.css';
import pretendardRegular from './_constants/font';
import { MSWComponent } from '@/public/mocks/MSWComponent';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${pretendardRegular.className}`}>
        <MSWComponent>{children}</MSWComponent>
      </body>
    </html>
  );
}
